[package]
name = "galaxycamel"
version = "0.1.1"
license = "MIT"
upgrade_policy = "compatible"

[addresses]
galaxycamel ="_"
std="0x1"
aptos_framework="0x1"
aptos_std="0x1"
aptos_token="0x3"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="aptos-cli-v1.0.0" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-stdlib/", rev="aptos-cli-v1.0.0" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-token/", rev="aptos-cli-v1.0.0" }